name: Deploy Website

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'static/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: lts/*
      - run: npm install -g surge
      - run: npm install
      - run: npm run build
      - run: cp dist/index.html dist/200.html
      - run: surge dist --domain https://${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
